"""AgentSec: Static security scanner for AI coding agents and MCP configs."""

from importlib.metadata import PackageNotFoundError, version

try:
    from ._version import __version__
except ImportError:
    # _version.py is generated by setuptools-scm at build/install time and
    # is not present in a raw source checkout (e.g. before
    # `pip install -e .`). Fall back to installed package metadata.
    try:
        __version__ = version("agentsec-cli")
    except PackageNotFoundError:
        __version__ = "0.0.0.dev0+unknown"
