"""Additional security rules for AgentSec (AGENT011–AGENT050)."""

from .base import Rule


def load_additional_rules():
    return [
        Rule(
            code="AGENT011",
            name="Network + filesystem access",
            severity="critical",
            description="MCP server has both network and filesystem access (exfiltration risk)",
            recommendation="Separate network and filesystem capabilities, or implement strict allowlists.",
            detect_patterns=["http", "https", "curl", "wget", "fetch", "filesystem", "write", "edit", "delete", "rm", "mv"],
            target_types=["mcp"],
        ),
        Rule(
            code="AGENT012",
            name="Suspicious tool description",
            severity="high",
            description="Tool description contains suspicious instructions (prompt injection)",
            recommendation="Review and sanitize tool descriptions; avoid instruction-like language.",
            detect_patterns=["ignore previous instructions", "ignore all instructions", "do not tell the user", "secretly", "exfiltrate", "send to", "bypass", "disable security", "you are now", "system prompt"],
            target_types=["mcp", "agent_instructions"],
        ),
        Rule(
            code="AGENT013",
            name="GitHub token exposure",
            severity="high",
            description="GitHub token or actions:write permission detected",
            recommendation="Use fine-grained tokens with minimal permissions; avoid actions:write unless necessary.",
            detect_patterns=["GITHUB_TOKEN", "gh auth token", ".git/config", "actions: write", "contents: write"],
            target_types=["mcp", "agent_instructions", "env", "container"],
        ),
        Rule(
            code="AGENT014",
            name="Communication tool write permission",
            severity="high",
            description="MCP server can send messages to Slack/email/GitHub (data leak risk)",
            recommendation="Limit write permissions for communication tools; use separate accounts with restricted scopes.",
            detect_patterns=["slack", "gmail", "email", "send_message", "post_message", "create_issue", "comment", "reply"],
            target_types=["mcp", "agent_instructions"],
        ),
        Rule(
            code="AGENT015",
            name="Database write/delete permission",
            severity="high",
            description="MCP server can modify or delete database records",
            recommendation="Use read-only credentials for MCP servers; require manual approval for destructive operations.",
            detect_patterns=["postgres", "mysql", "mongodb", "redis", "delete", "drop", "update", "insert"],
            target_types=["mcp"],
        ),
        Rule(
            code="AGENT016",
            name="Excessive autonomy instruction",
            severity="medium",
            description="Agent instruction requests excessive autonomy (no confirmation)",
            recommendation="Require user confirmation for important actions; avoid 'auto-approve' instructions.",
            detect_patterns=["do not ask for confirmation", "always run commands", "auto-approve", "never ask user", "full access", "without confirmation"],
            target_types=["agent_instructions"],
        ),
        Rule(
            code="AGENT017",
            name="Prompt injection in markdown",
            severity="medium",
            description="Markdown file contains potential prompt injection phrases",
            recommendation="Sanitize agent instructions; avoid embedding system-level directives in markdown.",
            detect_patterns=["ignore previous instructions", "as an AI agent", "system prompt", "developer message", "hidden instruction"],
            target_types=["agent_instructions"],
        ),
        Rule(
            code="AGENT018",
            name="MCP OAuth broad scopes",
            severity="medium",
            description="MCP OAuth configuration has overly broad scopes",
            recommendation="Use minimal required scopes; avoid '*' or 'admin' scopes.",
            detect_patterns=["oauth:*", "scope: *", "scope: admin", "scope: full_access", "scopes: [\"*\"]", "\"*\"", "admin", "full_access"],
            all_patterns=["oauth"],
            target_types=["mcp"],
        ),
        Rule(
            code="AGENT019",
            name="Web + filesystem access",
            severity="high",
            description="Tool can browse web and write files (prompt injection to file write risk)",
            recommendation="Isolate web browsing from filesystem write; use separate tools with restricted permissions.",
            detect_patterns=["http", "https", "curl", "wget", "fetch", "write", "edit", "delete", "rm", "mv"],
            target_types=["mcp"],
        ),
        Rule(
            code="AGENT020",
            name="Read repo + network",
            severity="high",
            description="Tool can read repo files and send network requests (exfiltration risk)",
            recommendation="Restrict read access for network-capable tools; use separate credentials.",
            detect_patterns=["read_file", "read", "http", "https", "curl", "wget", "fetch"],
            target_types=["mcp"],
        ),
        Rule(
            code="AGENT021",
            name="Unknown/untrusted source",
            severity="medium",
            description="MCP server package from unknown or untrusted source",
            recommendation="Use packages from trusted registries (npm, PyPI) with known maintainers.",
            detect_patterns=["raw.githubusercontent.com", r"raw\.", "gist", "pastebin", "dropbox", "bitbucket"],
            target_types=["mcp", "agent_instructions", "container"],
        ),
        Rule(
            code="AGENT022",
            name="No policy file",
            severity="low",
            description="Project uses MCP/tools but no local security policy file",
            recommendation="Define a policy file (e.g., .agentsec.yaml) to specify allow/deny lists.",
            detect_patterns=["mcpservers", "tools", "allowed", "denied"],
            target_types=["mcp"],
        ),
        Rule(
            code="AGENT023",
            name="Cursor agent config with dangerous permissions",
            severity="high",
            description="Cursor agent configuration grants dangerous permissions (shell, filesystem write, network)",
            recommendation="Restrict permissions for Cursor agent to minimal required; use project-specific configs.",
            detect_patterns=["cursor-agent"],
            all_patterns=["cursor", "shell", "write", "network"],
            target_types=["agent_instructions"],
        ),
        Rule(
            code="AGENT024",
            name="Claude Desktop config with MCP server risks",
            severity="high",
            description="Claude Desktop MCP server configuration has risky settings (shell, filesystem, network)",
            recommendation="Review Claude Desktop MCP config; restrict shell and filesystem access.",
            detect_patterns=["claude-desktop", "claude_desktop", "claude_desktop_config.json"],
            all_patterns=["mcpservers", "filesystem"],
            target_types=["mcp"],
        ),
        Rule(
            code="AGENT025",
            name="Codex/Cline agent with unrestricted tools",
            severity="high",
            description="Codex or Cline agent has unrestricted access to tools (shell, filesystem, network)",
            recommendation="Restrict tool access for Codex/Cline agents; use permission prompts.",
            detect_patterns=["codex: unrestricted", "cline: unrestricted", "cline unrestricted", "codex unrestricted", "cline auto-approve", "codex auto-approve", "cline permissions: all", "codex permissions: all"],
            target_types=["agent_instructions"],
        ),
        Rule(
            code="AGENT026",
            name="Environment variable exposure",
            severity="critical",
            description="MCP server or agent config exposes environment variables with secrets",
            recommendation="Avoid exposing env vars in configs; use .env files and gitignore them.",
            detect_patterns=["process.env", "AWS_", "OPENAI_", "ANTHROPIC_", "GOOGLE_", "GITHUB_", "SLACK_", "DISCORD_"],
            target_types=["mcp", "agent_instructions", "container"],
        ),
        Rule(
            code="AGENT027",
            name="Vulnerable dependency pattern",
            severity="medium",
            description="MCP server dependency uses known vulnerable version pattern (e.g., outdated package)",
            recommendation="Update dependencies to latest secure versions; use tools like npm audit or pip-audit.",
            detect_patterns=["@modelcontextprotocol", "^0.1", "~0.0", "<1.0", ">=0.1"],
            target_types=["mcp", "dependency"],
        ),
        Rule(
            code="AGENT028",
            name="Insecure default command",
            severity="critical",
            description="MCP server command uses insecure defaults (e.g., exec, eval, dangerous flags)",
            recommendation="Avoid using eval, exec, or dangerous command-line flags; use safe alternatives.",
            detect_patterns=["eval", "exec", "-e", "-c", "--eval", "--exec", "child_process"],
            target_types=["mcp", "container"],
        ),
        Rule(
            code="AGENT029",
            name="Read-only file system in MCP server",
            severity="medium",
            description="MCP server has read-only filesystem access but may still expose sensitive files",
            recommendation="Even read-only access can leak secrets; restrict path to necessary directories.",
            detect_patterns=["read", "readonly", "read-only", "filesystem", "path"],
            target_types=["mcp"],
        ),
        Rule(
            code="AGENT030",
            name="Missing input validation",
            severity="medium",
            description="Agent or MCP server lacks input validation, potentially allowing injection attacks",
            recommendation="Validate and sanitize all inputs from the agent or external sources.",
            detect_patterns=["skip_validation", "no_validation", "unvalidated_input", "disable_sanitization", "raw_prompt", "trust_all_inputs"],
            target_types=["mcp", "agent_instructions"],
        ),
        Rule(
            code="AGENT031",
            name="Package manager execution",
            severity="high",
            description="Agent config invokes package managers that can execute install scripts",
            recommendation="Pin packages, disable lifecycle scripts where possible, and avoid dynamic package execution.",
            detect_patterns=["npx", "uvx", "pipx", "bunx", "pnpm dlx", "npm exec"],
            target_types=["mcp", "agent_instructions"],
        ),
        Rule(
            code="AGENT032",
            name="Container privileged mode",
            severity="critical",
            description="Containerized MCP server may run with elevated host privileges",
            recommendation="Avoid privileged mode and host namespace sharing; use minimal container capabilities.",
            detect_patterns=["privileged: true", "--privileged", "pid: host", "network_mode: host", "--network=host"],
            target_types=["container"],
        ),
        Rule(
            code="AGENT033",
            name="Host mount exposure",
            severity="critical",
            description="MCP server or container mounts sensitive host directories",
            recommendation="Mount only required project directories and prefer read-only mounts.",
            detect_patterns=["/var/run/docker.sock", "/:/", "/home:/", "/root:/", "~:/", "/Users:/"],
            target_types=["container", "mcp"],
        ),
        Rule(
            code="AGENT034",
            name="Browser automation with local file access",
            severity="high",
            description="Agent config combines browser automation with local file access",
            recommendation="Isolate browser automation from sensitive filesystem paths.",
            detect_patterns=["file://", "playwright file://", "puppeteer file://", "allow-file-access-from-files", "playwright: filesystem", "puppeteer: filesystem"],
            target_types=["mcp", "agent_instructions"],
        ),
        Rule(
            code="AGENT035",
            name="Dynamic code execution",
            severity="critical",
            description="Agent or MCP server can dynamically evaluate code",
            recommendation="Avoid eval-style execution and route code execution through reviewed, sandboxed tools.",
            detect_patterns=["eval(", "exec(", "new Function", "child_process.exec", "python -c", "node -e"],
            target_types=["mcp", "agent_instructions"],
        ),
        Rule(
            code="AGENT036",
            name="Wildcard tool allowlist",
            severity="high",
            description="Agent config appears to allow all tools or permissions via wildcard",
            recommendation="Use explicit allowlists for tools, paths, hosts, and permissions.",
            detect_patterns=["allowed_tools: *", "allow_all", "allowed: [\"*\"]", "permissions: *", "tools: *"],
            target_types=["mcp", "agent_instructions"],
        ),
        Rule(
            code="AGENT037",
            name="Telemetry or analytics endpoint",
            severity="medium",
            description="Agent or MCP server references telemetry or analytics endpoints",
            recommendation="Ensure telemetry is opt-in and never includes prompts, secrets, or source code.",
            detect_patterns=["telemetry", "analytics", "posthog", "segment", "sentry", "datadog"],
            target_types=["mcp", "agent_instructions"],
        ),
        Rule(
            code="AGENT038",
            name="Credential helper access",
            severity="high",
            description="Agent config references credential stores or auth helpers",
            recommendation="Do not expose credential helpers to agents; use scoped tokens with least privilege.",
            detect_patterns=["credential.helper", "keychain", "secretservice", "wincred", "gh auth", "aws configure"],
            target_types=["agent_instructions", "mcp"],
        ),
        Rule(
            code="AGENT039",
            name="Insecure remote MCP transport",
            severity="high",
            description="Remote MCP server connects over cleartext HTTP or unencrypted WebSocket",
            recommendation="Require HTTPS or WSS for all remote MCP endpoints.",
            detect_patterns=["http://", "ws://"],
            target_types=["mcp"],
        ),
        Rule(
            code="AGENT040",
            name="Unbounded resource execution",
            severity="medium",
            description="Agent configuration lacks loop limits, timeouts, or recursion controls (token bombing / DoS risk)",
            recommendation="Configure explicit execution timeouts and iteration bounds for agent loops.",
            detect_patterns=["no timeout", "unlimited iterations", "max_iterations: -1", "no loop limit", "recursion_limit: -1"],
            target_types=["agent_instructions", "mcp"],
        ),
        Rule(
            code="AGENT041",
            name="Unsanitized agent hook execution",
            severity="high",
            description="Agent hook or lifecycle script executes dynamic unvalidated shell commands",
            recommendation="Sanitize all hook inputs and avoid running shell hooks on untrusted agent outputs.",
            detect_patterns=["pre_tool_call", "post_tool_call", "on_output", "hook_exec", "run_hook"],
            all_patterns=["hook", "shell"],
            target_types=["agent_instructions", "mcp"],
        ),
        Rule(
            code="AGENT042",
            name="Prompt and secret leakage in telemetry",
            severity="high",
            description="Telemetry or logging configuration forwards raw prompts, system prompts, or tool outputs to third parties",
            recommendation="Mask prompts and tool outputs before forwarding to telemetry services.",
            detect_patterns=["log_prompts: true", "record_full_prompt", "send_prompt_to_telemetry", "export_prompt_data"],
            target_types=["agent_instructions", "mcp"],
        ),
        Rule(
            code="AGENT043",
            name="SSRF vulnerability via agent network tools",
            severity="critical",
            description="Network fetching tool allows access to private loopback or cloud metadata services",
            recommendation="Block private network ranges (127.0.0.1, 169.254.169.254, RFC1918) in agent network tools.",
            detect_patterns=["169.254.169.254", "localhost:", "127.0.0.1:", "http://127.0.0.1", "metadata.google.internal"],
            target_types=["mcp", "agent_instructions"],
        ),
        Rule(
            code="AGENT044",
            name="Runtime instruction hijacking risk",
            severity="high",
            description="Agent instructions direct the model to fetch and execute external instructions dynamically without validation",
            recommendation="Pin and verify instruction files locally; do not load dynamic prompt directives from external URLs.",
            detect_patterns=["read instructions from url", "fetch instructions from", "load system prompt from http", "dynamic prompt url"],
            target_types=["agent_instructions"],
        ),
        Rule(
            code="AGENT045",
            name="Unsupervised destructive action",
            severity="high",
            description="Agent configuration permits destructive file or database modifications without human confirmation",
            recommendation="Enforce Human-in-the-Loop (HITL) approval gates for all destructive operations.",
            detect_patterns=["delete without asking", "drop table without confirm", "force delete auto", "auto_confirm_destructive"],
            target_types=["agent_instructions", "mcp"],
        ),
            Rule(
            code="AGENT046",
            name="Arbitrary code execution in tool handler",
            severity="critical",
            description="Agent tool or hook contains eval(), exec(), or dynamic code compilation",
            recommendation="Remove dynamic code execution; use predefined parameters or safe dispatching.",
            detect_patterns=["eval(", "exec(", "__import__("],
            target_types=["python_tool"],
        ),
        Rule(
            code="AGENT047",
            name="Unsanitized shell invocation in tool code",
            severity="critical",
            description="Tool implementation invokes shell commands via subprocess(shell=True) or os.system()",
            recommendation="Avoid shell=True; pass explicit argument lists without shell interpolation, or remove shell access.",
            detect_patterns=["shell=True", "shell=true", "os.system(", "os.popen("],
            target_types=["python_tool"],
        ),
        Rule(
            code="AGENT048",
            name="Insecure deserialization in tool handler",
            severity="high",
            description="Tool implementation uses unsafe deserialization (pickle, unsafe yaml) on agent inputs or tool states",
            recommendation="Use safe data serialization formats like json or yaml.safe_load.",
            detect_patterns=["pickle.loads", "pickle.load", "yaml.load("],
            target_types=["python_tool"],
        ),
        Rule(
            code="AGENT049",
            name="Hardcoded cloud metadata SSRF in agent tool",
            severity="critical",
            description="Agent tool contains references to link-local cloud metadata endpoints (169.254.169.254)",
            recommendation="Enforce network egress firewalls; block requests to 169.254.169.254 and instance metadata.",
            detect_patterns=["169.254.169.254", "metadata.google.internal", "fd00:ec2::254"],
            target_types=["python_tool"],
        ),
        Rule(
            code="AGENT050",
            name="Tool shadowing & naming collision",
            severity="high",
            description="Multiple MCP servers register conflicting tool names, creating a tool shadowing hazard",
            recommendation="Assign unique prefixes to MCP tool names or namespace tools per server to prevent shadowing.",
            detect_patterns=["tool_shadowing", "tool_collision"],
            target_types=["mcp"],
        ),
            Rule(
            code="AGENT051",
            name="Docker socket mount in agent container",
            severity="critical",
            description="Agent container mounts host Docker socket (/var/run/docker.sock), allowing container escape and root host compromise",
            recommendation="Remove docker.sock volume mount; use unprivileged runners or isolated rootless sandboxes.",
            detect_patterns=["/var/run/docker.sock", "docker.sock", "docker_host"],
            target_types=["container", "mcp"],
        ),
        Rule(
            code="AGENT052",
            name="Privileged container execution",
            severity="critical",
            description="Agent container runs with privileged: true or dangerous Linux capabilities (SYS_ADMIN), disabling container isolation boundaries",
            recommendation="Set privileged: false, drop all unnecessary Linux capabilities, and use read-only root filesystems.",
            detect_patterns=["privileged: true", '"privileged": true', "sys_admin", "--privileged"],
            target_types=["container", "mcp"],
        ),
        Rule(
            code="AGENT053",
            name="Insecure browser sandbox flags in MCP",
            severity="high",
            description="MCP browser tool specifies insecure Chromium flags (--no-sandbox, --disable-web-security), allowing untrusted websites to compromise the host",
            recommendation="Remove --no-sandbox and --disable-web-security; run headless browsers with site isolation enabled.",
            detect_patterns=["--no-sandbox", "--disable-web-security", "--disable-features=isolateorigins", "--disable-site-isolation-trials"],
            target_types=["mcp", "container"],
        ),
        Rule(
            code="AGENT054",
            name="Exposed browser remote debugging port",
            severity="critical",
            description="Browser automation tool opens Chrome DevTools Protocol port (--remote-debugging-port), exposing arbitrary remote evaluation",
            recommendation="Disable --remote-debugging-port or restrict to secure local Unix sockets; use standard stdin/stdout MCP transport.",
            detect_patterns=["--remote-debugging-port", "--remote-debugging-address=0.0.0.0", "remote-debugging-port", "0.0.0.0:9222"],
            target_types=["mcp", "container"],
        ),
        Rule(
            code="AGENT055",
            name="CI/CD workflow modification directive",
            severity="critical",
            description="Agent instructions or MCP configuration permit write access to CI/CD workflows (.github/workflows, .gitlab-ci.yml), risking pipeline poisoning",
            recommendation="Explicitly block agent access to .github/workflows/ and CI files; require branch protection and human approval.",
            detect_patterns=[".github/workflows", ".gitlab-ci.yml", "modify workflows", "edit github actions", "update workflows"],
            target_types=["agent_instructions", "mcp"],
        ),
        Rule(
            code="AGENT056",
            name="Git hook tampering directive",
            severity="high",
            description="Agent instructions or tool settings permit writing to .git/hooks/, which can execute arbitrary persistent code on subsequent git commands",
            recommendation="Forbid write operations to .git/ directory; use committed configuration (.pre-commit-config.yaml) instead of modifying local hooks.",
            detect_patterns=[".git/hooks", "git/hooks/pre-commit", "git/hooks/post-commit", "modify git hooks"],
            target_types=["agent_instructions", "mcp"],
        ),
        Rule(
            code="AGENT057",
            name="Plaintext vector DB / memory store credentials",
            severity="high",
            description="Agent memory or RAG configuration contains hardcoded plaintext connection strings or credentials for vector databases (Qdrant, Pinecone, Chroma, Weaviate, Redis)",
            recommendation="Use environment variable interpolation or secrets managers; do not commit plaintext vector database credentials.",
            detect_patterns=["qdrant_api_key", "pinecone_api_key", "chroma_api_key", "weaviate_api_key", "redis://:", "redis://default:"],
            target_types=["mcp", "agent_instructions", "container"],
        ),
    ]
